name: CD

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1

  npm-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          rm -rf .yarnrc.yml .yarn yarn.lock
          corepack enable 
      - run: |
          yarn set version stable
          yarn config set -H enableImmutableInstalls false
          yarn install
      - run: yarn workspace @escape.tech/graphql-armor install
      - run: yarn workspace @escape.tech/graphql-armor build
      - run: yarn workspace @escape.tech/graphql-armor publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
