name: CD

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1

  npm-release:
    defaults:
      run:
        working-directory: ./packages/graphql-armor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}'
      - run: corepack enable
      - run: yarn workspaces focus @escape.tech/graphql-armor
      - run: yarn workspace @escape.tech/graphql-armor build
      - run: yarn npm publish --access public
